In [4]:
import numpy as np

m = np.matrix([[0, 0, 6, 0],[0, 4,0,0], [3, 0, 8, 0]]) 
print("XD)")
print(m)

XD)
[[0 0 6 0]
 [0 4 0 0]
 [3 0 8 0]]


In [5]:
a = np.cov(m)
a

array([[ 9.        , -2.        , 10.5       ],
       [-2.        ,  4.        , -3.66666667],
       [10.5       , -3.66666667, 14.25      ]])

In [3]:
m1 = np.matrix([[0, 0, 3],[0, 4,0], [6, 0, 8], [0,0,0]]) 
a1 = np.cov(m1)
a1

array([[ 3.        , -2.        ,  5.        ,  0.        ],
       [-2.        ,  5.33333333, -9.33333333,  0.        ],
       [ 5.        , -9.33333333, 17.33333333,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [6]:
m1

matrix([[0, 0, 3],
        [0, 4, 0],
        [6, 0, 8],
        [0, 0, 0]])

In [37]:
 from sklearn.decomposition import PCA
 X = np.array([[0, 0, 3],
               [0, 6,0],
                [6, 0, 8],
                [0,0,0]])
#  X = np.array([[0, 0, 6, 0],[0, 6,0,0], [3, 0, 8, 0]])

 pca = PCA(n_components=3)
 pca.fit(X)
print(pca.components_)
print(pca.n_components_)
print(pca.explained_variance_ratio_)
print(pca.singular_values_)
B = pca.transform(X)
print(B)


[[ 0.56098153 -0.36389033  0.74356139]
 [ 0.3469329   0.91886705  0.1879386 ]
 [-0.7516231   0.15253582  0.64171297]]
3
[0.77095766 0.20906576 0.01997658]
[8.63655911 4.49745624 1.3902281 ]
[[-0.10974644 -1.85171526  1.05905916]
 [-4.52377264  3.0976712   0.0491352 ]
 [ 6.97394971  1.16957513 -0.24211461]
 [-2.34043063 -2.41553107 -0.86607975]]


In [40]:
from sklearn.decomposition import PCA
X = np.array([[0, 0, 3],
               [0, 6,0],
                [6, 0, 8],
                [0,0,0]])


pca = PCA(n_components=1)
pca.fit(X)
B = pca.transform(X)
print(pca.explained_variance_)

print(B)
X.var()
pca.explained_variance

[24.8633844]
[[-0.10974644]
 [-4.52377264]
 [ 6.97394971]
 [-2.34043063]]


8.409722222222223

In [1]:
import numpy as np

X = np.array([[0,0,6,0],

              [0,6,0,0],

              [3,0,8,0]]).astype(np.float64)

X = X - np.mean(X, axis=0)

n,m = X.shape

cov_np = np.cov(X, rowvar=False)

eigenvalues, eigenvectors = np.linalg.eig(cov_np)

print(np.round(eigenvectors[:,:3], 2))

[[-0.21  0.88 -0.43]
 [ 0.62  0.46  0.64]
 [-0.76  0.13  0.64]
 [ 0.    0.    0.  ]]
